---
title: "Demo - Lattice"
output: github_document
---

```{r}
library(lattice)

timeSeries2 <- read.csv("../data/TimeSeries2.csv")
head(timeSeries2)

```

## Horizontal Facet

Create horizontal facets

```{r}
title <- "Box Office Revenue by Year and Rating"
x_lab <- "Year"
y_lab <- "Box Office Revenue ($M)"


xyplot(
  data = timeSeries2,
  x = Box.Office ~ Year | Rating,
  type = "l",
  layout = c(4,1),
  main = title,
  xlab=x_lab,
  ylab = y_lab)

```

## Vertical Facet

Create vertical facets

```{r}
xyplot(
  data = timeSeries2,
  x = Box.Office ~ Year | Rating,
  type = "l",
  layout = c(1,4),
  main = title,
  xlab =x_lab,
  ylab = y_lab)
```

## Wrapped Facet

```{r}
xyplot(
  data = timeSeries2,
  x = Box.Office ~ Year | Rating,
  main = title,
  xlab = x_lab,
  ylab = y_lab,
  layout = c(2,2),
  type = "l")
```

## Load row-based time series

```{r}
timeSeries3 <- read.csv("../data/TimeSeries3.csv")
head(timeSeries3)
```

## 2D Faceted grid (Horizontal)
Create a 2-dimensional faceted grid

```{r}
title <- "Box Office Revenew by Year, Rating and Awards"

xyplot(
  x = Box.Office ~ Year | Rating * Awards,
  data = timeSeries3,
  type = "l",
  main = title,
  xlab = x_lab,
  ylab = y_lab)
```

## 2D Faceted grid (Vertical)
Create a 2-dimensional faceted grid

```{r}
xyplot(
  data = timeSeries3,
  x = Box.Office ~ Year | Awards * Rating,
  type = "l",
  main = title,
  xlab = x_lab,
  ylab = y_lab)
```

