---
title: "Trivariate Quantitative Analysis"
output: github_document
---

# Trivariate Quantitative Analysis

Setting up environment

```{r}
library(tidyverse)
library(RColorBrewer)
library(lattice)
gradient <- brewer.pal(5, "YlOrRd")
palette(gradient)
movies <- read.csv("../data/movies.csv")
movies2014 <- movies[movies$Year == 2014,]
```

# Chart and Plots

## Gradient Color-scale Scatterplot

```{r}

  xyplot(
    data = movies2014,
    x = Critic.Score ~ Runtime,
    col = gradient[cut(movies2014$Box.Office, 5)],
    pch = 16,
    main = "Runtime, Critic Score, and Box Office Revenue",
    xlab = "Runtime (min)",
    ylab = "Critic Score (%)",
    key = list(
      corner = c(0.05,0.05),
      title = "Box Office ($M)",
      cex = 0.75,
      text = list(levels(cut(movies2014$Box.Office,5))),
      points = list(
        pch = 16,
        col = gradient)))
```

## Divergent Color-scale Scatterplot

```{r}
divergent <- rev(brewer.pal(5,"RdBu"))
palette(divergent)

xyplot(
    data = movies2014,
    x = Critic.Score ~ Runtime,
    col = divergent[cut(movies2014$Box.Office, 5)],
    pch = 16,
    main = "Runtime, Critic Score, and Box Office Revenue",
    xlab = "Runtime (min)",
    ylab = "Critic Score (%)",
    key = list(
      corner = c(0.05,0.05),
      title = "Box Office ($M)",
      cex = 0.75,
      text = list(levels(cut(movies2014$Box.Office,5))),
      points = list(
        pch = 16,
        col = divergent)))
```

## Bubble Chart

Setting up environment
```{r}
getSize <- function(values, scale){
  ratio <- values / max(values)
  size <- sqrt(ratio/pi)
  size * scale
}
```


```{r}
xyplot(
  data = movies2014,
  x = Critic.Score ~ Runtime,
  cex = getSize(movies$Box.Office,5),
  main = "Runtime, Critic Score, and Box Office Revenue",
  xlab = "Runtime (min)",
  ylab = "Critic Score (%)")
```

## 3D Scatterplot

```{r}

cloud(
  x = Box.Office ~ Critic.Score * Runtime,
  data = movies2014,
  type = c("p","h"), # point and histagram
  pch = 16,
  main = "Runtime, Critic Score, and Box Office Revenue",
  xlab = "Runtime (min)",
  ylab = "Critic Score (%)",
  zlab = "Box Office\nRevenue\n($M)")
```
