---
title: "Qualitative Trivariate Analysis"
output: github_document
---

# Charts

```{r}
movies <- read.csv("../data/movies.csv")
head(movies)
```

Function to creat Contingency tables

```{r}
getTable <- function(distribution){
  filter <- movies$Distribution == distribution
  subset <- movies[filter,]
  table(
    x = subset$Awards,
    y = subset$Rating)
}
```

Displaying contingency tables

```{r}
getTable("Domestic")
```
```{r}
getTable("International")
```


## Faceted Grouped Frequency Bar Chart


```{r}
par(mfrow = c(1,2))
domestic_axes_title <- "Domestic"
international_axes_title <- "International"
rating_axes_title <- "Rating"
count_movies_axes_title <- "Count of Movies"

barplot(
  height = getTable("Domestic"),
  beside = TRUE,
  ylim = c(0,600),
  main = domestic_axes_title,
  xlab = rating_axes_title,
  ylab = count_movies_axes_title)

barplot(
  height = getTable("International"),
  beside = TRUE,
  ylim = c(0,600),
  main = international_axes_title,
  xlab = rating_axes_title,
  legend = rownames(getTable("International")))


```



## Faceted Stacked Frequency Bar Chart

```{r}
par(mfrow = c(1,2))
barplot(
  height = getTable("Domestic"),
  beside = FALSE, # Default
  ylim = c(0,1000),
  main = domestic_axes_title,
  xlab = rating_axes_title,
  ylab = count_movies_axes_title)

barplot(
  height = getTable("International"),
  ylim = c(0,1000),
  beside = FALSE, # Default
  main = domestic_axes_title,
  xlab = rating_axes_title,
  legend = rownames(getTable("International")))

```


## Faceted Frequency Bar Chart

Function to create frequency table

```{r}
getTable2 <- function(awards, distribution){
  
  filter <- movies$Awards == awards & movies$Distribution == distribution
  subset <-movies[filter, ]
  table(subset$Rating)
}
```

Print frequency tables

```{r}
getTable2("No Awards", "Domestic")
getTable2("Won Awards","Domestic")
getTable2("No Awards","International")
getTable2("Won Awards","International")
```

Charts

```{r}
par(mfrow = c(2,2))

barplot(
  height = getTable2("No Awards", "Domestic"),
  ylim = c(0,600),
  main = "No Awards / Domestic",
  ylab = "Count of Movies")


barplot(
  height = getTable2("Won Awards", "Domestic"),
  ylim = c(0,600),
  main = "Won Awards / Domestic")


barplot(
  height = getTable2("No Awards", "International"),
  ylim = c(0,600),
  main = "No Awards / International",
  ylab = "Count of Movies",
  xlab = "Rating")


barplot(
  height = getTable2("Won Awards", "International"),
  ylim = c(0,600),
  main = "Won Awards / International",
  xlab = "Rating")


```


```{r}
par(mfrow= c(1,1)) # Reset the default behavior
```



