---
title: "Qualitative Trivariate Analysis"
output: github_document
---

# Charts

```{r}
library(tidyverse)
library(lattice)
movies <- read.csv("../data/movies.csv")
head(movies)
```

We need to create a three-way contingency table

```{r}
table <- movies %>%
  select(Rating, Awards, Distribution) %>%
  group_by(Rating, Awards, Distribution) %>%
  summarize(Count= n())

head(table)
```

## Faceted Grouped Frequency Bar Chart

```{r}
table %>%
  barchart(
    x = Count ~ Rating | Distribution,
    groups = Awards,
    main = "Count of Movies by Rating, Awards, and Distribution",
    xlab = "Rating",
    ylab = "Count of Movies",
    auto.key = TRUE) # Let Lattice to generate the legend.
```



## Faceted Stacked Frequency Bar Chart

```{r}
table %>%
  barchart(
    x = Count ~ Rating | Distribution,
    groups = Awards,
    stack = TRUE,
    main = "Count of Movies by Rating, Awards, and Distribution",
    xlab = "Rating",
    ylab = "Count of Movies",
    auto.key = TRUE) # Let Lattice to generate the legend.


```


## Faceted Frequency Bar Chart

```{r}

table %>%
  barchart( 
    x = Count ~ Rating | Awards * Distribution,
    main = "Count of Movies by Rating, Awards, and Distribution",
    xlab = "Rating",
    ylab = "Count of Movies",
    auto.key = TRUE) # Let Lattice to generate the legend.

```

