---
title: "Qualitative Trivariate Analysis"
output: github_document
---

# Charts

```{r}
library(tidyverse)
movies <- read.csv("../data/movies.csv")
head(movies)
```



## Faceted Grouped Frequency Bar Chart

```{r}

movies %>%
  ggplot(
   aes(x=Rating, fill = Awards)) +
  geom_bar(
    position = "dodge") +
  facet_wrap(
    facets = ~Distribution) +
  ggtitle("Count of Movies by Rating, Awards, and Distribution")+
  xlab("Rating")+
  ylab("Count of Movies")
```


## Faceted Stacked Frequency Bar Chart

```{r}
movies %>%
  ggplot(
    aes(x = Rating, fill = Awards)) +
  geom_bar() +
  facet_wrap(
    facets = ~Distribution) +
  ggtitle("Count of Movies by Rating, Awards, and Distribution")+
  xlab("Rating")+
  ylab("Count of Movies")
```


## Faceted Frequency Bar Chart

```{r}
movies %>%
  ggplot(aes(x = Rating)) +
  geom_bar() +
  facet_grid(
    facets = Awards ~ Distribution) +
  ggtitle("Count of Movies by Rating, Awards, and Distribution")+
  xlab("Rating")+
  ylab("Count of Movies")
```

