---
title: "Trivariate Analysis for 1 Quantitative and 2 Qualitative variables"
output: github_document
---


# Charts

Setting up environment

```{r}
library(lattice)
library(RColorBrewer)
library(tidyverse)
colors <- brewer.pal(4, "Set1")
shapes <- c(1,4,2,0)
movies <- read.csv("../data/movies.csv")
movies2014 <- movies[movies$Year == 2014,]

```


## Color-coded Scatterplot

```{r}
movies2014 %>%
xyplot(
  x = Box.Office ~ Critic.Score,
  group = Rating,
  par.settings = list(
    superpose.symbol = list(
      col = colors)),
  auto.key = list(columns = 4),
  main = "Critic Score vs Box Office Revenue by Rating",
  xlab = "Critic Score (%)",
  ylab = "Box Office Revenue ($M)")
```

## Shaped-coded Scatterplot

```{r}
movies2014 %>%
xyplot(
  x = Box.Office ~ Critic.Score,
  key = list(
    text = list(
      levels(movies2014$Rating)),
    points = list(
      pch = shapes),
    columns = 4),
  pch = shapes[as.integer(movies2014$Rating)],
  main = "Critic Score vs Box Office Revenue by Rating",
  xlab = "Critic Score (%)",
  ylab = "Box Office Revenue ($M)")

```

## Faceted Scatterplot

```{r}
movies2014 %>%
  xyplot(
    x = Box.Office ~ Critic.Score | Rating,
    main = "Critic Score vs Box Office Revenue by Rating",
    xlab = "Critic Score (%)",
    ylab = "Box Office Revenue ($M)")
```

## Multi-series Line Chart

Setting up environment
```{r}
timeSeries2 <- movies %>%
  select(Year, Rating, Box.Office) %>%
  group_by(Year, Rating) %>%
  summarize(Box.Office = mean(Box.Office)) %>%
  as.data.frame()
head(timeSeries2)
```

Plotting

```{r}
xyplot(
  x = Box.Office ~ Year,
  data = timeSeries2,
  groups =  Rating,
  type = "l",
  auto.key = list(columns = 4),
  main = "Box Office Revenue over Time by Rating",
  xlab = "Year",
  ylab = "Box Office Revenue ($M)")


```

## Stacked Area Chart

**Stacked Area chart is a bit difficult on the base chart control, so we are doing it on GGPlot**

## Faceted Line Chart

```{r}
xyplot(
  x = Box.Office ~ Year | Rating,
  data = timeSeries2,
  type = "l",
  layout = c(2,2),
  main = "Box Office Revenue over Time by Rating",
  xlab = "Year",
  ylab = "Box Office Revenue ($M)")
```

