---
title: "Trivariate Analysis for 1 Quantitative and 2 Qualitative variables"
output: github_document
---


# Charts

Setting up environment

```{r}
library(tidyverse)
library(RColorBrewer)
colors <- brewer.pal(4,"Set1")
shapes <- c(1,4,2,0)
movies <- read.csv("../data/movies.csv")
movies2014 <- movies[movies$Year == 2014,]

```


## Color-coded Scatterplot

```{r}
movies2014 %>%
  ggplot(
    aes(x = Critic.Score, 
        y = Box.Office,
        color = Rating)) +
  scale_color_manual(
    name = "Rating",
    labels = levels(movies2014$Rating),
    values = colors) +
  geom_point() +
  ggtitle("Critic Score vs Box Office Revenue by Rating") +
  xlab("Critic Score") +
  ylab("Box Office Revenue ($M)")
```

## Shaped-coded Scatterplot

```{r}
movies2014 %>%
  ggplot(
    aes(x = Critic.Score, 
        y = Box.Office,
        shape = Rating)) +
  scale_shape_manual(
    name = "Rating",
    labels = levels(movies2014$Rating),
    values = shapes) +
  geom_point() +
  ggtitle("Critic Score vs Box Office Revenue by Rating") +
  xlab("Critic Score") +
  ylab("Box Office Revenue ($M)")
```

## Faceted Scatterplot

```{r}
movies2014 %>%
  ggplot(
    aes(x = Critic.Score, 
        y = Box.Office)) +
  geom_point() +
  facet_wrap(
    facets =  ~Rating) +
  ggtitle("Critic Score vs Box Office Revenue by Rating") +
  xlab("Critic Score") +
  ylab("Box Office Revenue ($M)")
```

## Multi-series Line Chart

Setting up environment
```{r}
timeSeries2 <- movies %>%
  select(Year, Rating, Box.Office) %>%
  group_by(Year, Rating) %>%
  summarize(Box.Office = mean(Box.Office)) %>%
  as.data.frame()
head(timeSeries2)
```



```{r}
timeSeries2 %>%
  ggplot(
    aes(
      x = Year,
      y = Box.Office,
      color = Rating)) +
  geom_line() +
  ggtitle("Box Office Revenue over Time by Rating") +
  xlab("Year") +
  ylab("Box Office Revenue ($M)")
```

## Stacked Area Chart

```{r}
timeSeries2 %>%
  ggplot(
    aes(
      x = Year,
      y = Box.Office,
      fill = Rating)) +
  geom_area() +
  ggtitle("Box Office Revenue over Time by Rating") +
  xlab("Year") +
  ylab("Box Office Revenue ($M)")
```

## Faceted Line Chart

```{r}
timeSeries2 %>%
  ggplot(
    aes(
      x = Year,
      y = Box.Office)) +
  geom_line() +
  facet_wrap(
    facets = ~Rating) +
  ggtitle("Box Office Revenue over Time by Rating") +
  xlab("Year") +
  ylab("Box Office Revenue ($M)")
```

